# Day 3

## **Improting**

In [13]:
import numpy as np

### Step 1: Represent three data samples as a (3 × features) NumPy matrix.

In [14]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]    
])
print(arr)
print("Shape: ",arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)


### Step 2:  Compute the dot product of one sample vector with a weight vector by hand, then verify it with np.dot.

In [15]:
sample = np.array([1,2,3])
weight = np.array([4,5,6])
manual = (1*4)+(2*5)+(3*6)
print ("Manual veification: ", manual)
print("Verify with np.dot: ", np.dot(sample,weight))

Manual veification:  32
Verify with np.dot:  32


### Step 3: Use matrix multiplication (@) to produce a prediction for all three samples at once.

In [16]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]    
])
x= np.array([0.5,0.75,0.9])
multi = arr @ x
print("Multiplication: ",multi)

Multiplication:  [ 4.7  11.15 17.6 ]


### Step 4:Deliberately create a shape-mismatch error, read the message, and explain in Markdown why it 
### occurred and how to fix it.

In [17]:
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]    
])
x1= np.array([0.5,0.75])
multi = arr1 @ x1
print(multi)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

## Shape Mismatch Error

The dataset matrix `arr1` has a shape of `(3, 3)`, which means it contains 3 samples and 3 features.

The weight vector `x1` has a shape of `(2,)`, so it only contains weights for 2 features.

Matrix multiplication requires the number of columns in the matrix to match the number of elements in the weight vector.

Since the inner dimensions do not match (`3 ≠ 2`), NumPy raises a `ValueError`.

### How to Fix It

Use a weight vector with one weight for each feature.

```python
x = np.array([0.5, 0.75, 0.9])
predictions = arr @ x
```

Now the shapes are compatible:

- `X`: `(3, 3)`
- `weights`: `(3,)`

The matrix multiplication works successfully and returns one prediction for each sample.